name: clean_arch_movie_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_rating_bar: ^4.0.1
  rxdart: ^0.27.5
  shared_preferences: ^2.2.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.1
  flutter_native_splash: ^2.2.19
  connectivity_plus: ^5.0.2
  easy_localization: ^3.0.1
  mockito: ^5.4.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  json_serializable:
  json_annotation:
  bloc_test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    exclude:
      # - assets/images/chip3/chip3.jpg
      # - pictures/chip5.jpg
      # - assets/flare/

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/
    - assets/translations/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-Light.woff
          weight: 300
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.woff
          weight: 400
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.woff
          weight: 500
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.woff
          weight: 700
        - asset: assets/fonts/GoogleSans/GoogleSans-Black.woff
          weight: 800
